version: '3.2'
services:
  db:
    image: postgres:9.6
    #restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - data-db:/var/lib/postgresql/data
    ports:
      - 5432:5432


  odoo:
    build: ./odoo
    #restart: always
    depends_on:
      - db
    volumes:
      - "data-odoo:/data/odoo"
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=asterisk
      - ADMIN_PASSWD=admin-change-me
      - RUNNING_ENV=dev
      - MARABUNTA_FORCE_VERSION=1.0.0
      #- MARABUNTA_MODE=demo
      - LOG_HANDLER=:WARN
    ports:
      - 8069:8069
      - 8072:8072


  # can be useful for dev when longpolling is required
  nginx:
    image: camptocamp/odoo-nginx:9.0-1.1.0
    depends_on:
      - odoo
    ports:
      - 80:80

  asterisk:
    build:  asterisk
    depends_on:
      - db
    environment:
      - ODOO_HOST=${ODOO_HOST:-odoo}
      - PG_DB_NAME=asterisk
      - PG_DB_HOST=${PG_DB_HOST:-db}
      - PG_DB_USER=odoo
      - PG_DB_PASSWORD=odoo
      - HTTP_ENABLED=yes
      - MANAGER_ENABLED=yes
      - MANAGER_WEB_ENABLED=yes
      - MANAGER_LOGIN=odoo
      - MANAGER_PASSWORD=odoo
    network_mode: host


volumes:
  data-odoo:
  data-db:
    external: true
