---
- hosts: all
  gather_facts: no
  become: yes


  vars:
    asterisk_version: 13.10.0
    asterisk_src_dir: /home/asterisk/src
    asterisk_prefix: /srv/asterisk
    asterisk_user: asterisk
    asterisk_group: asterisk


  roles:
    - asterisk

